config/routes.rb
Afisha::Application.routes.draw do
  
  match "/", to: redirect("/lv")
  
  scope "(:locale)", locale: /lv|ru/ do
    devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
    resources :users, only: :show

    # match "/:locale/:id"  => "events#show"
    resources :events, except: :show

    root to: 'application#index'
  end
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  attr_accessible :title_en, :title_lv, :description_lv, :title_ru, :description_ru, :trailer, :poster
  has_attached_file :poster, styles: { medium: "300x300>", thumb: "120x170>" },
                    convert_options: { thumb: "-quality 96" }

  include FriendlyId
  friendly_id :title_lv, use: [:slugged, :simple_i18n]

  def slug locale
    "/#{locale}/#{locale == 'ru' ? self.slug_ru : self.slug_lv }"
  end

  def title locale
    locale == 'ru' ? self.title_ru : self.title_lv
  end

  def description locale
    locale == 'ru' ? self.description_ru : self.description_lv
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/showtime.rb
class Showtime < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :omniauthable, :trackable

  attr_accessible :name, :email, :password, :provider, :uid

  def self.find_for_facebook_oauth access_token
    if user = User.where(email: access_token.extra.raw_info.email).first
      user
    else 
      User.create!(provider: access_token.provider, provider: access_token.provider,
                   name: access_token.extra.raw_info.name, uid: access_token.uid, 
                   email: access_token.extra.raw_info.email, password: Devise.friendly_token[0,20]) 
    end
  end

  def fullname
    name.presence || email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  before_filter :set_locale
 
  def set_locale
    @locale = I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index    
    render json: Event.all
# [{
#   id: 1,
#   title_lv: 'lv 1',
#   title_en: '1'
# }, {
#   id: 2,
#   title_lv: 'lv 2',
#   title_en: '2'
# }, {
#   id: 3,
#   title_lv: 'lv 3',
#   title_en: '3'
# }, {
#   id: 4,
#   title_lv: 'lv 4',
#   title_en: '4'
# }, {
#   id: 5,
#   title_lv: 'lv 5',
#   title_en: '5'
# }, {
#   id: 6,
#   title_lv: 'lv 6',
#   title_en: '6'
# }]
  end

  def show
    # @multikino = Multikino.new(Date.tomorrow)
    # @multikino_showtimes = @multikino.get_showtimes
    
    # @forumcinemas = Forumcinemas.new(Date.tomorrow)
    # @forumcinemas_showtimes = @forumcinemas.get_showtimes

    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])
    @event.set_friendly_id(params[:event][:title_ru], :ru)

    if @event.save
      redirect_to @event.slug
    else
      render action: "new"
    end
  end

  def update
    @event = Event.find(params[:id])
    
    if @event.update_attributes(params[:event])
      redirect_to @event.slug
    else
      render action: "edit"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to "/"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    user = User.find_for_facebook_oauth request.env["omniauth.auth"]
    if user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    # @multikino    = Multikino.new(Date.tomorrow)
    # @multikino_lv = @multikino.get_lv_movies
    # @multikino_ru = @multikino.get_ru_movies
    
    # @forumcinemas = Forumcinemas.new(Date.tomorrow)    
    # @forumcinemas_lv = @forumcinemas.get_lv_movies
    # @forumcinemas_ru = @forumcinemas.get_ru_movies
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= f.label :title_en %>  
<div class="controls"><%= f.text_field :title_en %></div>

<%= f.label :title_lv %>  
<div class="controls"><%= f.text_field :title_lv %></div>

<%= f.label :description_lv %>  
<div class="controls"><%= f.text_area :description_lv, rows: 4 %></div>

<%= f.label :title_ru %>  
<div class="controls"><%= f.text_field :title_ru %></div>

<%= f.label :description_ru %>  
<div class="controls"><%= f.text_area :description_ru, rows: 4 %></div>

<%= f.label :trailer %>  
<div class="controls"><%= f.text_field :trailer %></div>

<%= f.label :poster %>  
<div class="controls"><%= f.file_field :poster %></div>

<div class="actions">
  <%= f.submit "Сохранить" %>
  <%= link_to "Отменить", "/" %>
</div>

app/views/events/_movies.html.erb
<h2>MultikinoLV</h2>

<table>
  <th>
    <tr>
      <td>title</td>
      <td>showings</td>
      <td>description</td>
      <td>url</td>
    </tr>
  </th>
  <% @multikino_showtimes.each do |movie|%>
    <tr>
      <td><%= movie[:title] %></td>
      <td><%= movie[:showings].join(", ") %></td>
      <td><%= movie[:description] %></td>
      <td><%= movie[:url] %></td>
    </tr>
  <% end %>
</table>

<hr>

<h2>ForumcinemasLV</h2>

<table>
  <th>
    <tr>
      <td>title</td>
      <td>showings</td>
      <td>description</td>
      <td>url</td>
    </tr>
  </th>
  <% @forumcinemas_showtimes.each do |movie| %>
    <tr>
      <td><%= movie[:title] %></td>
      <td><%= movie[:showings].join(", ") %></td>
      <td><%= movie[:description] %></td>
      <td><%= movie[:url] %></td>
    </tr>
  <% end %>
</table>

app/views/events/edit.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="container">

    <h1>Редактировать мероприятие</h1>
    <%= form_for @event, url: event_path(@locale, @event.id), method: "put",  html: { multipart: true } do |f| %>
      <%= render 'form', f: f %>
    <% end %>

  </div>
</div>

app/views/events/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="container">
    
    <ul>
    <% @events.each do |event| %>      
      <li>
        <%= link_to image_tag(event.poster.url(:thumb)), event.slug(@locale) %>
        <%= link_to event.title(@locale), event.slug(@locale) %>
      </li>
    <% end %>
    </ul>

  </div>
</div>

<%#= render "movies" %>

app/views/events/new.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="container">

    <h1>Добавить мероприятие</h1>
    <%= form_for @event, html: { multipart: true } do |f| %>
      <%= render 'form', f: f %>
    <% end %>

  </div>
</div>

app/views/events/show.html.erb
<%= render "shared/header" %>

<div class="main">
    
  <div class="event_details">

    <div>
      <%= link_to "edit", edit_event_path(@locale, @event.id) %> | 
      <%= link_to "delete", event_path(@locale), confirm: 'Are you sure?', method: "delete" %>
    </div>

    <h1><%= @event.title(@locale) %></h1>

    <% if @event.trailer.present? %>
      <iframe width="560" height="315" src="http://www.youtube-nocookie.com/embed/<%= @event.trailer.split("?v=")[1] %>?rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
    <% end %>

    <%= image_tag @event.poster, width: 200 %>

    <%= @event.description(@locale) %>  
  </div>

  <div class="event_showtime">
    <div class="showtime_block">
      <select name="period" class="chzn-select" style="width: 100%;">
        <option value="1">Сегодня</option>
        <option value="2">Завтра</option>
      </select>

      <a href="" class="place">Forumcinemas</a>
      <a href="" style="color: #ccc;">10:00</a>, <a href="">12:00</a>, <a href="">14:00</a>

      <a href="" class="place">Cinamon</a>
      10:00, 12:00, 14:00
    </div>
  </div>

</div>


<%#= render "movies" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Afisha</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700&subset=latin,latin-ext,cyrillic' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_header.html.erb
<div class="header">
  <div class="container">
    <div class="brand">
      <a href="/<%= @locale %>">1Afisha</a>
      <a href="/lv">lv</a>
      <a href="/ru">ru</a>

      <a href="/<%= @locale %>/events/new">add event</a>
    </div>
    <div class="user">
      <% if user_signed_in? %>
        <img src="https://graph.facebook.com/<%= current_user.uid %>/picture" class="avatar">
        <%= current_user.fullname %>  <%= link_to t('logout'), destroy_user_session_path %>
      <% else %>
        <%= link_to t('login'), user_omniauth_authorize_path(:facebook) %>
      <% end %>  
    </div>
  </div>
</div>